service: CHANGEME

plugins:
  - serverless-domain-manager
  - serverless-v2-aws-documentation
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  profile: serverless
  stage: dev
  region: us-east-1

  lambdaHashingVersion: 20201221

  logs:
    restApi: true

  tracing:
    apiGateway: true
    lambda: true

  environment:
    DEBUG: ${self:custom.environment.debugLog}
    NODE_ENV: ${self:custom.environment.nodeEnvironment}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

  domainName: ${self:custom.domainNameStage.${self:custom.stage}}
  domainNameStage:
    dev: 'localhost:${self:custom.serverless-offline.httpPort}'
    test: test-api.${self:custom.baseDomainName}
    prod: api.${self:custom.baseDomainName}
  baseDomainName: CHANGEME
  customDomain:
    domainName: ${self:custom.domainName}
    certificateName: ${self:custom.domainName}
    basePath: CHANGEME
    stage: ${self:custom.stage}
    createRoute53Record: true

  serverless-offline:
    httpPort: '3000'
    websocketPort: '3001'
    lambdaPort: '3002'

  environment:
    debugLog: ${self:custom.environment.debugLogStage.${self:custom.stage}}
    debugLogStage:
      dev: 'CHANGEME:*,-*:trace'
      test: 'CHANGEME:*,-*:trace'
      prod: 'CHANGEME:*,-*:trace'
    nodeEnvironment: ${self:custom.environment.nodeEnvironmentStage.${self:custom.stage}}
    nodeEnvironmentStage:
      dev: development
      test: test
      prod: production

  documentation:
    info:
      title: CHANGEME
      description: CHANGEME
      version: 1.0.0

package:
  individually: false

  exclude:
    - .circleci/**
    - .github/**
    - .idea/**
    - .env*
    - examples/**
    - scripts/**
    - spec/**
    - tmp/**

functions:
  graphql:
    handler: dist/events/apollo.handler
    events:
      - http:
          path: graphql
          method: get
          cors: true
          documentation:
            summary: GraphQL Server
            description: GraphQL Server

      - http:
          path: graphql
          method: post
          cors: true
          documentation:
            summary: GraphQL Server
            description: GraphQL Server
