name: CI
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1-alpine
      options: --user root

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: ls -l /__w/node-aws-lambda-graphql-sapling
      - run: which npm
      - run: ls -l /usr/local/bin
      - run: whoami
      - run: sh -e npm run whoami
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test -- --ci --maxWorkers=1 --reporters=default
